package com.cotisapp.domain.enums;

public enum PosteMembre {
    SIMPLE,
    PRESIDENT,
    VICE_PRESIDENT,
    SECRETAIRE_GENERAL,
    SECRETAIRE_GENERAL_ADJOINT,
    TRESORIER,
    TRESORIER_ADJOINT,
    COMMISSAIRE_AUX_COMPTES,
    SUPERVISEUR
}
